const { test, expect } = require('@playwright/test');
const path = require('node:path');
const fs = require('node:fs');
const output = '/tmp/camaze-insights-screenshots';
test('recorded-usage path and fictional samples render without overflow', async ({ page }, info) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/insights.html');
  await expect(page.locator('#status')).toContainText('No comparison available');
  await expect(page.locator('#coverage')).toContainText('gpt-4o-2024-11-20');
  await expect(page.locator('#coverage')).toContainText('Exact model or version unsupported');
  await expect(page.getByText('LOCAL PREVIEW:', { exact: false })).toBeVisible();
  fs.mkdirSync(output, { recursive: true });
  await page.screenshot({ path: path.join(output, `${info.project.name}-recorded.png`), fullPage: true });
  await page.getByLabel('Sample examples', { exact: true }).check();
  await expect(page.locator('.insight')).toHaveCount(2);
  await expect(page.locator('#status')).toContainText('fictional');
  await expect(page.locator('#status')).toContainText('do not affect your spending');
  await page.locator('.insight summary').first().click();
  await expect(page.getByText('No personal savings are calculated.', { exact: false }).first()).toBeVisible();
  await page.screenshot({ path: path.join(output, `${info.project.name}-samples.png`), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Switch to dark theme' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.screenshot({ path: path.join(output, `${info.project.name}-samples-dark.png`), fullPage: true });
  expect(errors).toEqual([]);
  await page.getByLabel('Your usage', { exact: true }).check();
  await expect(page.locator('.insight')).toHaveCount(0);
  await expect(page.locator('#status')).toContainText('No comparison available');
});
test('loading, no usage, source failure and request failure states', async ({ page }) => {
  let finish;
  await page.route('**/api/insights', async route => {
    await new Promise(resolve => { finish = resolve; });
    await route.fulfill({ json: { period: { start: '2026-08-12', end: '2026-09-11' }, insights: [], unsupported: [], excluded: [], observedModels: 0, source: { status: 'error', ageDays: 8 } } });
  });
  await page.goto('/insights.html');
  await expect(page.locator('#status')).toHaveText('Loading recorded usage...');
  await expect.poll(() => Boolean(finish)).toBe(true);
  finish();
  await expect(page.locator('#status')).toContainText('No recorded usage');
  await expect(page.locator('#status')).toContainText('refresh failed');
  await expect(page.locator('#status')).toContainText('older than 7 days');
  await page.unroute('**/api/insights');
  await page.route('**/api/insights', route => route.fulfill({ status: 503, json: { error: 'Unavailable' } }));
  await page.reload();
  await expect(page.locator('#status')).toContainText('could not be loaded');
  await page.getByLabel('Sample examples', { exact: true }).check();
  await expect(page.locator('.insight')).toHaveCount(2);
});
